language: node_js
node_js:
  - "6.11"

before_script:
  - npm install -g
  - npm install -g @angular/cli
  - npm install primeng

script:
  - ng build --prod

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

deploy:  
 provider: azure_web_apps
 skip_cleanup: true
 file: "dist/*"
 on:
    branch: master

notifications:
  email:
    on_failure: change
    on_success: change