language: node_js
node_js:
  - "8.6"

before_install:
  - sudo apt-get install ncftp

before_script:
  - npm install
  - npm install -g @angular/cli

script:
  - ng build --prod --aot=false

after_success:
  -  ncftpput -R -u "$AZURE_WA_USERNAME" -p "$AZURE_WA_PASSWORD" $AZURE_WA_FTP site/wwwroot dist/*